# Generated by Django 3.2.4 on 2021-07-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='items')),
                ('description', models.TextField(default='This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.')),
                ('price', models.IntegerField(default=0)),
                ('slug', models.SlugField(default='')),
            ],
            options={
                'verbose_name': 'Items on sale',
                'ordering': ['title'],
            },
        ),
    ]
