# Generated by Django 3.2.4 on 2021-07-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
