# Generated by Django 3.2.4 on 2021-08-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-added_on'], 'verbose_name': 'Project', 'verbose_name_plural': 'Project'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='created_on',
            new_name='added_on',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='technology',
            new_name='framework',
        ),
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(default='Python', max_length=255),
            preserve_default=False,
        ),
    ]
