# Generated by Django 3.2.4 on 2021-07-01 10:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 7, 1, 10, 10, 54, 170447, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
