# Generated by Django 3.2.4 on 2021-07-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210701_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='last_modified',
            field=models.DateTimeField(verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(verbose_name='Date Modified'),
        ),
    ]
