# Generated by Django 3.2.4 on 2021-07-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210701_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='last_modified',
            field=models.DateTimeField(),
        ),
    ]
