# Generated by Django 3.2.4 on 2021-07-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='edited',
            field=models.CharField(default='', max_length=255),
        ),
    ]
